INSERT INTO CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
VALUES(10001,'USD','INR',83,'');


INSERT INTO CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
VALUES(10002,'SGD','INR',62,'');


INSERT INTO CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
VALUES(10003,'CAD','INR',53,'');